version: '3.8'

services:
  app:
    build: .
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "8001:80"  # Ensure this port is free
    command: nodemon server.js
    environment:
      - NODE_ENV=development

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: VvphRVaIHGzWXhEwcnPWUbYxfnkbJSaO
      POSTGRES_DB: railway
